### ISSUE TITLE
Upgrade CLHM to v1.4.2

### ISSUE THREAD

**Issue by ben-manes** [grails-plugins/grails-cache#21]
An upgrade is probably worthwhile to resolve a memory issue, fixed in [1.4.2](https://code.google.com/p/concurrentlinkedhashmap/wiki/Changelog#Version_1.4.2_(Released:_1/2015)). If a future Grails version requires Java 1.8, please consider migrating to [Caffeine](https://github.com/ben-manes/caffeine).

**Comment by graemerocher** [comment]
Done. Thanks
