### ISSUE TITLE
Support usage without spring proxy

### ISSUE THREAD

**Issue by jameskleeh** [grails-plugins/grails-cache#23]
Ideally this would be done similar to `@Transactional` to stop the usage of spring proxys. This is the kind of code that I would like to see no longer necessary

```
class AbcService {

  def grailsApplication

  @Cacheable("myCache")
  def list(String role) {
  ...
  }

  def adminList() {
    grailsApplication.mainContext.abcService.list("ROLE_ADMIN")
  }
}
```

**Comment by graemerocher** [comment]
Yup would definitely be nice, hopefully one day all proxies will die
