### ISSUE TITLE
Controller method caching does not work

### ISSUE THREAD

**Issue by jtruty** [grails-plugins/grails-cache#24]
Copying issue from other repo: https://github.com/grails3-plugins/cache/issues/3

**Comment by jtruty** [comment]
Any known workarounds?

**Comment by pjdvmalan** [comment]
I am experiencing the same issue:
- Grails 3.1.12
- Gradle dependencies: compile "org.grails.plugins:cache:3.0.3

Is this a known issue, or do I need to send  example code?

**Comment by mpccolorado** [comment]
Same in here :(

**Comment by jameskleeh** [comment]
Version 4.0.0 of the plugin will not support this feature
