### ISSUE TITLE
After a cache entry expires, all cache queries cause loads until one load finishes

### ISSUE THREAD

**Issue by gregopet** [grails-plugins/grails-cache#38]
We have a Grails 3.1.6 application using grails-cache 3.0.2 and ehcache 2.0.0.BUILD-SNAPSHOT

One of our applications came under heavier-than-usual load lately and we've started experiencing slowdowns with a period matching one of our caches' expiry interval. By turning on logging for the cache loading function we've determined that when a cache item expires, all cache fetches will trigger database loads until the first one of them finishes and the cache is populated again (which makes performance even worse since the queries are now competing for resources). The behaviour we expected was that the cache should be aware that it is loading a key's entry already and wait for that call to complete.

The call is from a controller to a service method with a single parameter of type `Long`. The cache configuration looks like this:

```
<cache name="cache-name"
       maxEntriesLocalHeap="100"
       maxEntriesLocalDisk="0"
       overflowToDisk="false"
       eternal="false"
       timeToIdleSeconds="60"
       timeToLiveSeconds="60"
       memoryStoreEvictionPolicy="LFU">
</cache>
```

**Comment by jameskleeh** [comment]
This issue belongs in the ehcache plugin's issue tracker. Please verify it happens with the latest milestone release
