### ISSUE TITLE
Add a package name to `DefaultCacheConfig` 

### ISSUE THREAD

**Issue by jjchiw** [grails-plugins/grails-cache#40]
Hi

I'm trying to get rid off all the `WARN` messages when grails is booting and I found this one

```
ERROR --- [           main] g.boot.config.tools.ClassPathScanner     : The application defines a Groovy source using the default package. Please move all Groovy sources into a package.
```

Then to verify which Groovy sources is using the default package I ran in the Console

```
ctx.grailsApplication.allClasses.findAll { !it.getPackage() }*.name
```

And this was the result

```
['DefaultCacheConfig', 'ConsoleUrlMappings']
```

So I came here searched for [`DefaultCacheConfig`](https://github.com/grails-plugins/grails-cache/blob/master/grails-app/init/DefaultCacheConfig.groovy) and as `ClassPathScanner` `DefaultCacheConfig` is not in a package....

I'm using:
```
| Grails Version: 3.2.4
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_112
| grails-cache Version: 3.0.3
```

Thanks :)

**Comment by hamza3202** [comment]
@jjchiw I thought that this was the issue as well for me so i tried removing the cache plugin but the error was still there, can you confirm that it is the same for you as well?

**Comment by jameskleeh** [comment]
The current way of supplying config has been removed in 4.0.0

**Comment by danduke** [comment]
Where can we get 4.0.0?  Looks like 3.0.3 is still the latest here: https://bintray.com/grails/plugins/cache

Also, still accurate that 4.0.0 will require GORM 6.1?

**Comment by jameskleeh** [comment]
4.0.0 is coming soon, and yes. 4.0.0.BUILD-SNAPSHOT could be used today
