### ISSUE TITLE
org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.buildDelegatingMethodCall(Lorg/codehaus/groovy/control/SourceUnit;Lorg/codehaus/groovy/ast/AnnotationNode;Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/MethodNode;Lorg/codehaus/groovy/ast/expr/MethodCallExpression;Lorg/codehaus/groovy/ast/stmt/BlockStatement;)Lorg/codehaus/groovy/ast/expr/MethodCallExpression;

### ISSUE THREAD

**Issue by vahidhedayati** [grails-plugins/grails-cache#42]
Just checked the site and noticed there was an update, I have tried latest: 
```
compile 'org.grails.plugins:cache:4.0.0.M2'
```
on local project and it appears to behave the same as sample/demo project. https://github.com/vahidhedayati/testcache4

When attempting to run grails run-app it produces : 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.buildDelegatingMethodCall(Lorg/codehaus/groovy/control/SourceUnit;Lorg/codehaus/groovy/ast/AnnotationNode;Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/MethodNode;Lorg/codehaus/groovy/ast/expr/MethodCallExpression;Lorg/codehaus/groovy/ast/stmt/BlockStatement;)Lorg/codehaus/groovy/ast/expr/MethodCallExpression;
```

If i disable cache plugin the site works - or my other site did at least

**Comment by jameskleeh** [comment]
You can't put the annotation on a controller action, however it should throw an error stating that

**Comment by vahidhedayati** [comment]
Sure under 2 you could have it on controllers. Anyhow moved it to service method and still same problem i have updated the test site

**Comment by jameskleeh** [comment]
Using GORM 6.1.3 resolved the compilation issue

**Comment by jameskleeh** [comment]
> Sure under 2 you could have it on controllers

Not anymore.

**Comment by vahidhedayati** [comment]
Thank you James. updating it to 6.1.3 has now moved the problem on to cache name country not being valid aka something not right with config. It appears to be working
