### ISSUE TITLE
grails.cache.enabled = false

### ISSUE THREAD

**Issue by barcelona23** [grails-plugins/grails-cache#43]
In development time, I tried to disable the cache functionality.
The documentation says "grails.cache.enabled | true | Whether to enable the plugin"

When I use grails.cache.enabled = false, I'm getting the follow error:
![screen shot 2017-07-18 at 7 46 24 pm](https://user-images.githubusercontent.com/221474/28347078-32c08856-6bf2-11e7-9855-45914df94292.png)

Any idea? Or I'm missing something here

I'm using some <cache> tags for all project I would not like to change all them, just to work on development time.

**Comment by barcelona23** [comment]
**My Versions:**
Grails Version: 3.2.11
Groovy Version: 2.4.11
JVM Version: 1.8.0_131
cache:4.0.0.RC1
gormVersion=6.1.5.RELEASE

**Comment by jameskleeh** [comment]
Can you upload an example project?

**Comment by barcelona23** [comment]
Simple Demo.

[grailsCache.zip](https://github.com/grails-plugins/grails-cache/files/1157848/grailsCache.zip)

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails-plugins/grails-cache/commit/04d6fd10d608237c5d471f0ae531bfbc97fed9e0

Thanks for reporting!
