### ISSUE TITLE
[Static type checking] - The variable [key] is undeclared.

### ISSUE THREAD

**Issue by 112921482** [grails-plugins/grails-cache#45]
I coded like this:
    @Cacheable(value = "AuthToken", key = { key })
    def getAuthToken(String key) {
        return key
    }
but comes an error:
[Static type checking] - The variable [key] is undeclared.
Can u help me?

**Comment by 112921482** [comment]
I am so sorry. After I readed the docs carefully, I learned how to use this, thanks so much.

**Comment by zearic** [comment]
I just figure it out. just for other user that may have the similar error:  It looks like these annotations cannot be used in Controller. Once I've moved them to Service, they are all good now.

**Comment by linchanghui** [comment]
@zearic i have same problem.because i use groovy 2.x.i dont have upgrade groovy to 3.x. but i think groovy 3.x is ok. i fix this problem by downgrading to org.grails.plugins:cache:3.0.2. and use String type key.
