### ISSUE TITLE
Compile error for @Cacheable annotation when class is marked as @Transactional

### ISSUE THREAD

**Issue by davidbairdala** [grails-plugins/grails-cache#49]
```
import grails.gorm.transactions.Transactional
import grails.plugin.cache.*

@Transactional
class TestService {

    @Cacheable(value = 'testservice', key = { foobar.toLowerCase() } )
    String serviceMethod(String foobar) {
        return foobar
    }
}

```
yeilds the following compiler error
```
[Static type checking] - The variable [foobar] is undeclared.
 @ line 9, column 47.
   alue = 'testservice', key = { foobar.toL
```

If I remove the @Transactional annotation, it compiles and works as expected

**Comment by mkobel** [comment]
With `@Transactional` a static type check is enforced somehow.
If you add the `@groovy.transform.CompileDynamic` annotation to your service, you no longer have the compiler error. 

But this seems to be only a workaround.

Is there probably a [type checking extension](http://docs.groovy-lang.org/next/html/documentation/type-checking-extensions.html) required?

**Comment by timic** [comment]
Grails 3.3.x depends on 4.x version of this plugin. Since `@Transcational` annotation is widely used, this makes this plugin unusable and the migration to Grails 3.3.x is impossible.

Please release this fix ASAP.

**Comment by puneetbehl** [comment]
@timic I am not sure if I follow, do you mean releasing v4.0.2?
