### ISSUE TITLE
Cache Configuration for Limiting Entries not working in v5.0.0.RC1

### ISSUE THREAD

**Issue by jfrosch** [grails-plugins/grails-cache#69]
The issue logged at https://github.com/grails-plugins/grails-cache/issues/62 was closed as fixed in 4.0.3 of the plugin. However, the fix appears to have not have been merged into 5.0.0.RC1 needed for Grails 4.0.x.

The 5.0.0.RC1 release was last published in February 2019 and the 4.0.3 fix was completed in October 2019, thus still has the pre-4.0.03 non-static inner class which results in the originally documented issue.

Either the 4.0.3 changes should be merged to 5.0.0.RC1 or a new RC2 release should be created, then the updated 5.0.x release should be published.

**Comment by puneetbehl** [comment]
Fixed with 5.0.0
